[package]
name = "graph-server-metrics"
version = "0.22.0"
edition = "2018"

[dependencies]
futures = "0.3.13"
graph = { path = "../../graph" }
http = "1.1"
hyper = "1.2"
lazy_static = "1.2.0"
serde = "1.0"
